roster:
  - Luke
  - Rony
  - Dave
  - Ella
  - Aiden
  - Maria
  - Karla
  - Alex
  - Eric
  - Nick
  - Ben
  - Chris
  - Jon
  - Tyler
  - Adrianna
people_that_left: null
  # - Rony
num_races_each: 4
previous_races:
  - Aiden Nick Maria Dave
  - Eric Nick Jon Alex
  - Ben Alex Dave Karla
  - Luke Aiden Alex Chris
  - Aiden Jon Ella Karla
algorithmic:
  seed: 1
  num_trials: 10
  num_optimize_iterations: 20000
  initial_optimize_temperature: 1.0
  optimize_cooling_rate: 0.005
  num_swap_iterations: 500000
  initial_swap_temperature: 1.0
  swap_cooling_rate: 0.0001
